import { Product } from "./types";

export const products: Product[] = [

    {
        id:1,
        title:" Printed shirt",
        image:["/pictures/shirt9.webp"],
        slug:"printed-shirt",
        price:150,
        discount:40,
        category:"tops",
        description:"Beautiful printed shirt for Women",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },
    {
        id:2,
        title:"Light Brown Coat",
        image:["/pictures/coat.jpg"],
        slug:"brown-coat",
        price:299,
        discount:30,
        category:"tops",
        description:"Beautiful Light Brown Coat",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },
    {
        id:3,
        title:"Jogger Shoes",
        image:["/pictures/shoes4.webp"],
        slug:"joggers",
        price:450,
        discount:20,
        category:"shoes",
        description:"Beautiful Jogger Shoes for Women",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },
    {
        id:4,
        title:"Geans Pant",
        image:["/pictures/pant4.webp"],
        slug:"geans",
        price:180,
        discount:50,
        category:"pants",
        description:"Beautiful Geans Pant for Women",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },
    {
        id:5,
        title:"  Black glasses",
        image:["/pictures/glasses.webp"],
        slug:"black-glasses",
        price:180,
        discount:50,
        category:"accessories",
        description:"Beautiful Black glasses for Women in summer season",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },

    {
        id:6,
        title:"Golden watch",
        image:["/pictures/watch.jpg"],
        slug:"golden-watch",
        price:200,
        discount:20,
        category:"accessories",
        description:"Beautiful golden watchs for Women in every season",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },
    {
        id:7,
        title:"Women Bracelets",
        image:["/pictures/acesories3.jpg"],
        slug:"Bracelets",
        price:120,
        discount:50,
        category:"accessories",
        description:"Beautiful Women Bracelets",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },
    {
        id:8,
        title:"Light Pink Coat",
        image:["/pictures/coat3.webp"],
        slug:"coat",
        price:140,
        discount:20,
        category:"tops",
        description:"Beautiful Light Pink Coat",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },

    {
        id:9,
        title:"Black Hat",
        image:["/pictures/hat.jpg"],
        slug:"hat",
        price:120,
        discount:60,
        category:"accessories",
        description:"Beautiful Black Hat",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },
    {
        id:10,
        title:"Black Pant",
        image:["/pictures/pant2.webp"],
        slug:"pants",
        price:120,
        discount:50,
        category:"pants",
        description:"Beautiful Black Pant for Women",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },
    {
        id:11,
        title:"Red Pant",
        image:["/pictures/pant3.webp"],
        slug:"pant-red",
        price:110,
        discount:40,
        category:"pants",
        description:"Beautiful Red Pant for Women",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },
    {
        id:12,
        title:"Simple Shoes",
        image:["/pictures/shoes.jpg"],
        slug:"shoes",
        price:100,
        discount:70,
        category:"shoes",
        description:"Beautiful Simple Shoes for Women",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },
    {
        id:13,
        title:"Golden Locket",
        image:["/pictures/acesories4.webp"],
        slug:"locket",
        price:60,
        discount:50,
        category:"accessories",
        description:"Beautiful Golden Locket",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },
    {
        id:14,
        title:"Jogger Shoes",
        image:["/pictures/shoes3.webp"],
        slug:"pink-shoes",
        price:500,
        discount:40,
        category:"shoes",
        description:"Beautiful Jogger Shoes for Women",
       size: ["S","M","L","XL"],
       color: ["#ffffff", "#000000", "#e60000"],
       qty:1,
    },
   
  
];